{{- if .Values.serviceAccounts.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.api.name }}
  namespace: {{ include "venueops.namespace" . }}
  labels:
    app: {{ .Values.api.name }}
    {{- include "venueops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.serviceAccounts.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.api.automountServiceAccountToken }}
---
{{- end }}

{{- if .Values.serviceAccounts.ingestionApi.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.ingestionApi.name }}
  namespace: {{ include "venueops.namespace" . }}
  labels:
    app: {{ .Values.ingestionApi.name }}
    {{- include "venueops.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion-api
  {{- with .Values.serviceAccounts.ingestionApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.ingestionApi.automountServiceAccountToken }}
---
{{- end }}

{{- if .Values.serviceAccounts.web.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.web.name }}
  namespace: {{ include "venueops.namespace" . }}
  labels:
    app: {{ .Values.web.name }}
    {{- include "venueops.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.serviceAccounts.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.web.automountServiceAccountToken }}
{{- end }}
