{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: {{ .Values.storage.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ include "venueops.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
