{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: venueops-default-deny-ingress
  namespace: {{ include "venueops.namespace" . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx-to-venueops-web
  namespace: {{ include "venueops.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.web.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.web.port }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-venueops-web-to-api
  namespace: {{ include "venueops.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.api.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.web.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.api.port }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-venueops-web-to-ingestion-api
  namespace: {{ include "venueops.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.ingestionApi.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.web.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.ingestionApi.port }}
{{- end }}