apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuers.ca.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ca:
    secretName: {{ .Values.rootCA.secretName | quote }}