{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.serviceAccountName }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    app: prometheus
automountServiceAccountToken: true
{{- end }}

{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.serviceAccountName }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    app: grafana
automountServiceAccountToken: false
{{- end }}

{{- if .Values.nodeExporter.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeExporter.serviceAccountName }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    app: node-exporter
automountServiceAccountToken: false
{{- end }}

{{- if .Values.kubeStateMetrics.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubeStateMetrics.serviceAccountName }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    app: kube-state-metrics
automountServiceAccountToken: true
{{- end }}