{{- if .Values.nodeExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter

  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.nodeExporter.port | quote }}
        prometheus.io/path: /metrics

    spec:
      serviceAccountName: {{ .Values.nodeExporter.serviceAccountName }}
      automountServiceAccountToken: false
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
        - operator: Exists

      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image | quote }}
          imagePullPolicy: {{ .Values.nodeExporter.imagePullPolicy }}

          securityContext:
            {{- toYaml .Values.nodeExporter.containerSecurityContext | nindent 12 }}

          args:
            - "--path.rootfs=/host"
            - "--web.listen-address=0.0.0.0:{{ .Values.nodeExporter.port }}"

          ports:
            - name: metrics
              containerPort: {{ .Values.nodeExporter.port }}
              protocol: TCP

          readinessProbe:
            {{- toYaml .Values.nodeExporter.probes.readiness | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.nodeExporter.probes.liveness | nindent 12 }}

          volumeMounts:
            - name: rootfs
              mountPath: /host
              readOnly: true

          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}

      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
{{- end }}